#!/bin/bash

sudo yum install -y docker
sudo groupadd docker
sudo usermod -aG docker $(whoami)
sudo service docker start
# exit terminal and reload if docker still requires permissions
# restart docker if error still occurs
#sudo service docker restart

sudo curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
